name: Bug Report
description: Report a bug in Code Solver
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      placeholder: Describe the bug you encountered.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: Describe the steps to reproduce the error.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Code Solver Version
      placeholder: E.g., 1.0.1
    validations:
      required: true